### ISSUE TITLE
Параллельный запуск тестов с разными конфигурациями

### ISSUE THREAD

**Issue by shineqwe** [alexmorez/codeceptjs-testit-reporter#2]
Здравствуйте. 
Как хотел бы сделать:
- запустить параллельно тесты с разными конфигурациями, 
- результат поместить в один test-run

Возможно ли сделать такое?

**Comment by alexmorez** [comment]
Приветствую. В теории - возможно. В документации codeceptjs [есть примеры](https://codecept.io/parallel/#custom-parallel-execution), как запускать тесты на отдельных воркерах. Сходу выглядит так, будто бы достаточно: 
1. в адаптере добавить возможность отправлять результаты тестрана без его завершения
2. перед запуском воркеров создать тестран
3. запустить воркеры, настроив каждому свой инстанс адаптера, но пошарив ID тестрана
4. после завершения работы воркеров завершить тестран
